Fr/feature/reviews block
focusreactive/hardhat pull request #19
Opened 2022-04-03 16:52 UTC by Kragov

2022-04-04 13:47 UTC, usulpro requested changes

2022-04-04 13:47 UTC, usulpro commented on docs/src/components/landingBlocks/ReviewsBlock.tsx
> +    [content]
in what cases we expecting content to be changed?

2022-04-04 13:47 UTC, usulpro commented on docs/src/pages/_app.tsx
> +import "../styles/carousel.css";
why we importing styles globally if we need them only on a single page? can't we encapsulate them into component styles?

2022-04-04 13:47 UTC, usulpro commented on docs/src/styles/carousel.css
> +.carousel .control-arrow,
Can't we move it inside slider container styles?

2022-04-04 13:47 UTC, usulpro commented on docs/src/components/ui/default-props.ts
> +import VictorImage from "../../assets/images/victor.png";
Not in this PR but in the next one:
rename these things from defaultProps to home content and put it into `content/home`. Add props from `pages/index.tsx` as well

2022-04-04 18:04 UTC, Kragov commented on docs/src/components/landingBlocks/ReviewsBlock.tsx
> +    [content]
I guess we got none of them but eslint throws error if we will not provide it to dependencies

2022-04-04 18:07 UTC, Kragov commented on docs/src/pages/_app.tsx
> +import "../styles/carousel.css";
This is styles for carousel library. I'm not sure there are some way to move them inside component, we can discuss it on nearest sync

2022-04-04 18:12 UTC, Kragov commented on docs/src/styles/carousel.css
> +.carousel .control-arrow,
Well probably but I'm not sure it will work for slider library

2022-04-05 12:01 UTC, usulpro commented on docs/src/components/landingBlocks/ReviewsBlock.tsx
> +    [content]
yes because this construction is assumed that props could be changed. if dependency isn't changed why we need to memoize this?

2022-04-06 12:52 UTC, merged