Fr/feature/animations
focusreactive/hardhat pull request #53
Opened 2022-05-12 14:39 UTC by RavenInd

- Desktop animation
- Mobile animation
- Theme switcher styles

2022-05-16 13:03 UTC, usulpro requested changes

2022-05-16 13:03 UTC, usulpro commented on docs/src/components/DocsNavigation.tsx
> +          {theme === ThemesEnum.AUTO && "A "}
Can we plese wrap it into span and remove space (setup margin instead)

2022-05-16 13:03 UTC, usulpro commented on docs/src/components/landingBlocks/HeroBlock.tsx
> +        <Block>{isDesktop ? <DesktopAnimation /> : <MobileAnimation />}</Block>
This affects LCP metric

2022-05-16 13:03 UTC, usulpro commented on docs/src/components/landingBlocks/HeroBlock.tsx
> +        <Block>{isDesktop ? <DesktopAnimation /> : <MobileAnimation />}</Block>
![image](https://user-images.githubusercontent.com/14885189/168598551-f8634458-332b-4b82-a552-d9d2c606d13a.png)

2022-05-16 13:08 UTC, usulpro requested changes

2022-05-16 13:08 UTC, usulpro commented on docs/src/components/MobileAnimation.tsx
> +    const main = document.getElementById("main");
can't we get using React useRef API?

2022-05-16 13:43 UTC, RavenInd commented on docs/src/components/landingBlocks/HeroBlock.tsx
> +        <Block>{isDesktop ? <DesktopAnimation /> : <MobileAnimation />}</Block>
Used css instead

2022-05-16 13:44 UTC, RavenInd commented on docs/src/components/MobileAnimation.tsx
> +    const main = document.getElementById("main");
Switched to React useRef API

2022-05-16 13:48 UTC, RavenInd commented on docs/src/components/DocsNavigation.tsx
> +          {theme === ThemesEnum.AUTO && "A "}
I just deleted this space.
I believe that we don't need more space here

2022-05-18 14:34 UTC, usulpro approved these changes

2022-05-18 14:42 UTC, merged